# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.6.3

EAPI=8

CRATES="
	addr2line-0.17.0
	adler-1.0.2
	anyhow-1.0.66
	async-trait-0.1.58
	autocfg-1.1.0
	backtrace-0.3.66
	base64-0.13.1
	bitflags-1.3.2
	bumpalo-3.11.1
	bytes-1.2.1
	cc-1.0.76
	cfg-if-1.0.0
	ctor-0.1.26
	data-encoding-2.3.2
	encoding_rs-0.8.31
	enum-as-inner-0.5.1
	fnv-1.0.7
	form_urlencoded-1.1.0
	futures-0.3.25
	futures-channel-0.3.25
	futures-core-0.3.25
	futures-executor-0.3.25
	futures-io-0.3.25
	futures-macro-0.3.25
	futures-sink-0.3.25
	futures-task-0.3.25
	futures-util-0.3.25
	getrandom-0.2.8
	gimli-0.26.2
	h2-0.3.15
	hashbrown-0.12.3
	heck-0.4.0
	hermit-abi-0.1.19
	hostname-0.3.1
	http-0.2.8
	http-body-0.4.5
	httparse-1.8.0
	httpdate-1.0.2
	hyper-0.14.23
	hyper-rustls-0.23.1
	idna-0.2.3
	idna-0.3.0
	indexmap-1.9.1
	ipconfig-0.3.1
	ipnet-2.5.1
	itoa-1.0.4
	js-sys-0.3.60
	lazy_static-1.4.0
	libc-0.2.137
	linked-hash-map-0.5.6
	lock_api-0.4.9
	log-0.4.17
	lru-cache-0.1.2
	match_cfg-0.1.0
	matches-0.1.9
	memchr-2.5.0
	mime-0.3.16
	minidom-0.12.0
	miniz_oxide-0.5.4
	mio-0.8.5
	num_cpus-1.14.0
	object-0.29.0
	once_cell-1.16.0
	parking_lot-0.12.1
	parking_lot_core-0.9.4
	percent-encoding-2.2.0
	pin-project-lite-0.2.9
	pin-utils-0.1.0
	ppv-lite86-0.2.17
	proc-macro2-1.0.47
	quick-error-1.2.3
	quick-xml-0.17.2
	quote-1.0.21
	rand-0.8.5
	rand_chacha-0.3.1
	rand_core-0.6.4
	redox_syscall-0.2.16
	reqwest-0.11.13
	resolv-conf-0.7.0
	ring-0.16.20
	rustc-demangle-0.1.21
	rustls-0.20.7
	rustls-pemfile-1.0.1
	ryu-1.0.11
	scopeguard-1.1.0
	sct-0.7.0
	serde-1.0.147
	serde_derive-1.0.147
	serde_json-1.0.87
	serde_urlencoded-0.7.1
	simplelog-0.12.0
	slab-0.4.7
	smallvec-1.10.0
	socket2-0.4.7
	spin-0.5.2
	syn-1.0.103
	termcolor-1.1.3
	thiserror-1.0.37
	thiserror-impl-1.0.37
	time-0.3.17
	time-core-0.1.0
	time-macros-0.2.6
	tinyvec-1.6.0
	tinyvec_macros-0.1.0
	tokio-1.24.1
	tokio-macros-1.8.0
	tokio-rustls-0.23.4
	tokio-util-0.7.4
	tower-service-0.3.2
	tracing-0.1.37
	tracing-attributes-0.1.23
	tracing-core-0.1.30
	trust-dns-proto-0.22.0
	trust-dns-resolver-0.22.0
	try-lock-0.2.3
	unicode-bidi-0.3.8
	unicode-ident-1.0.5
	unicode-normalization-0.1.22
	untrusted-0.7.1
	url-2.3.1
	want-0.3.0
	wasi-0.11.0+wasi-snapshot-preview1
	wasm-bindgen-0.2.83
	wasm-bindgen-backend-0.2.83
	wasm-bindgen-futures-0.4.33
	wasm-bindgen-macro-0.2.83
	wasm-bindgen-macro-support-0.2.83
	wasm-bindgen-shared-0.2.83
	web-sys-0.3.60
	webpki-0.22.0
	webpki-roots-0.22.5
	widestring-0.5.1
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
	windows-sys-0.42.0
	windows_aarch64_gnullvm-0.42.0
	windows_aarch64_msvc-0.42.0
	windows_i686_gnu-0.42.0
	windows_i686_msvc-0.42.0
	windows_x86_64_gnu-0.42.0
	windows_x86_64_gnullvm-0.42.0
	windows_x86_64_msvc-0.42.0
	winreg-0.10.1
"

#DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=maturin
PYTHON_COMPAT=( python3_{10..12} )
inherit cargo distutils-r1

DESCRIPTION="Python manager for CMSIS-Pack index and cache with fast Rust backend"
HOMEPAGE="https://github.com/pyocd/cmsis-pack-manager"
SRC_URI="
	https://github.com/pyocd/${PN}/archive/v${PV}.tar.gz -> ${P}.gh.tar.gz
	$(cargo_crate_uris)
"
#S="${WORKDIR}/${P}"

LICENSE="Apache-2.0"
# Dependent crate licenses
LICENSE+="
	BSD ISC MIT MPL-2.0 Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
# FIXME: licenses for ring-0.16.20 webpki-0.22.0

SLOT="0"
KEYWORDS="~amd64"

RDEPEND="
	>=dev-python/appdirs-1.4[$PYTHON_USEDEP]
	=dev-python/appdirs-1*[$PYTHON_USEDEP]
	$(python_gen_cond_dep 'dev-python/cffi[${PYTHON_USEDEP}]' 'python*')
	=dev-python/pyyaml-6*[$PYTHON_USEDEP]
"

RESTRICT="test"
#distutils_enable_tests unittest
